version: "2"

services:

  web2004-php7:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PHP_VERSION=7.4
    environment:
      - MYSQL_ADMIN_PASS=password
    ports:
      - "3030:80"
      - "3031:3306"
    tmpfs:
      - /var/lib/mysql

  web2004-php8:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PHP_VERSION=8.0
    environment:
      - MYSQL_ADMIN_PASS=password
    ports:
      - "3040:80"
      - "3041:3306"
    tmpfs:
      - /var/lib/mysql
